# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dispatch_pb2 as dispatch__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServerStub:
    """The gRPC contract between the Rust router and the Python model server
    (docs/design/2026-09-20-phase-7-productionization.md SS3-4). Compiled
    by both sides -- tonic-build/prost-build (Rust, router/build.rs) and
    grpcio-tools (Python, scripts/gen_proto.py) -- each vendors its own
    protoc, so no system protoc install is required.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/dispatch.v1.ModelServer/Generate',
                request_serializer=dispatch__pb2.GenerateRequest.SerializeToString,
                response_deserializer=dispatch__pb2.GenerateResponse.FromString,
                _registered_method=True)


class ModelServerServicer:
    """The gRPC contract between the Rust router and the Python model server
    (docs/design/2026-09-20-phase-7-productionization.md SS3-4). Compiled
    by both sides -- tonic-build/prost-build (Rust, router/build.rs) and
    grpcio-tools (Python, scripts/gen_proto.py) -- each vendors its own
    protoc, so no system protoc install is required.
    """

    def Generate(self, request, context):
        """Streams generated text token-by-token. The final message in the
        stream always has is_final=true and empty text; every message
        before it has is_final=false and carries exactly one token's text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=dispatch__pb2.GenerateRequest.FromString,
                    response_serializer=dispatch__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispatch.v1.ModelServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispatch.v1.ModelServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelServer:
    """The gRPC contract between the Rust router and the Python model server
    (docs/design/2026-09-20-phase-7-productionization.md SS3-4). Compiled
    by both sides -- tonic-build/prost-build (Rust, router/build.rs) and
    grpcio-tools (Python, scripts/gen_proto.py) -- each vendors its own
    protoc, so no system protoc install is required.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dispatch.v1.ModelServer/Generate',
            dispatch__pb2.GenerateRequest.SerializeToString,
            dispatch__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
